name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v5
      # BEGIN
            - name: Install dependensies
        run: make setup
      - name: Run lint
        run: make lint
      - name: Run test
        run: make test
      # END
