name: Node CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - uses: actions/checkout@v7

      - uses: jdx/mise-action@v5
      # BEGIN
      - name: Install dependencies
        run: make setup
      - name: Run lint
        run: make lint
      - name: Run tests
        run: make test
      - name: Print Hello From Hexlet
        run: hexlet-components/hello-from-hexlet-action@release
      # END
